### ISSUE TITLE
model

### ISSUE THREAD

**Issue by krejcif** [magento-hackathon/AdminMenuManager#3]
Table amm_mapping

Columns 
- action (1 - create, 2 - move, 3 - rename, 4 - hide)
- source  (path to node)
- target (path to parent node)
- target_type (1 - link, 2 - heading)
- title (new name)
- icon (path ti icon file on disk)
- sort_order (order of added item)

**Comment by pgrigoruta** [comment]
Done

**Comment by pgrigoruta** [comment]
Done
